#!/bin/sh -eux

THIS_SCRIPT=$0
THIS_DIR=$(dirname ${THIS_SCRIPT})

. ${THIS_DIR}/_setup_environment


evaluate_last_week() {
  cd "${THIS_DIR}"
  python3 -m expirybot.evaluate_last_week
  cd -
}

evaluate_last_week
