#!/bin/sh -eux

THIS_SCRIPT=$0
THIS_DIR=$(dirname ${THIS_SCRIPT})

SHORT_IDS_FILE="${THIS_DIR}/data/$(date +%F)/short_key_ids.txt"


copy_short_ids_dump_file() {
  mkdir -p $(dirname $SHORT_IDS_FILE)

  if [ ! -f "${SHORT_IDS_FILE}" ]; then
    mv ${HOME}/short_key_ids_dump.txt "${SHORT_IDS_FILE}"
  fi
}

setup_dev_shm() {
  mkdir -p /dev/shm/tmp.expirybot
}

make_expiring_keys_csv() {
  cd "${THIS_DIR}"
  python3 -m expirybot.make_csv "${SHORT_IDS_FILE}"
  cd -
}

clean_dev_shm() {
  rm -rf /dev/shm/tmp.expirybot/
}

copy_short_ids_dump_file
setup_dev_shm
make_expiring_keys_csv
clean_dev_shm
